---
abstract: 'Bundle to install all TochkaK related Modules'
author:
  - 'Anatoly Sharifulin <sharifulin@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
keywords:
  - bundle
  - cpan
  - tk
  - tochkak
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bundle-TK
provides:
  Bundle::TK:
    file: lib/Bundle/TK.pm
    version: 1.05
requires:
  AnyEvent: 0
  AnyEvent::HTTP: 0
  Bundle::CPAN: 0
  Convert::Bencode: 0
  Data::GUID: 0
  Date::Calc: 0
  HTML::Template: 0
  HTTP::Date: 0
  IO::Socket::SSL: 0
  Image::Magick: 0
  JSON: 0
  List::MoreUtils: 0
  MIME::Lite: 0
  Math::Base36: 0
  Net::LastFM: 0
  Net::SNMP: 0
  Net::Server: 0
  Net::Twitter: 0
  POE: 0
  POE::Component::Client::DNS: 0
  POE::Component::Client::HTTP: 0
  POE::Component::Client::Icecast: 0
  POE::Component::Client::Keepalive: 0
  POE::Component::SSLify: 0
  POE::XS::Queue::Array: 0
  Sphinx::Search: 0
  Spreadsheet::WriteExcel: 0
  Template: 0
  Template::Plugin::JSON: 0
  Template::Plugin::String::Compare: 0
  TinyURL::RU: 0
  XML::LibXML: 0
  common::sense: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/sharifulin/Bundle-TK.git
version: 1.05
